# Generated by Django 2.2.1 on 2019-05-25 00:54

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ref_number',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, unique=True, uppercase=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='ref_number',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, unique=True, uppercase=True),
        ),
    ]
