# Generated by Django 2.2.1 on 2019-05-31 00:07

import cloudinary.models
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190525_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_num',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=5, uppercase=True),
        ),
    ]
