# Generated by Django 2.2.1 on 2019-06-04 16:40

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190604_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ref_number',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['union__name', 'id']),
        ),
    ]
