# Generated by Django 2.2.1 on 2019-06-04 17:39

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190604_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='ref_number',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['id', 'union__name', 'email']),
        ),
    ]
