# Generated by Django 2.2.2 on 2019-06-05 03:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190604_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ref_number',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['union__name'], separator='_'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qrcode',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
