# Generated by Django 2.2.2 on 2019-07-02 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190605_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=cloudinary.models.CloudinaryField(help_text='Profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
