# Generated by Django 2.2.2 on 2019-07-06 00:36

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190704_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
