# Generated by Django 2.2.3 on 2019-07-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_union_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='union',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='core.Union'),
            preserve_default=False,
        ),
    ]
