# Generated by Django 2.2.3 on 2019-07-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_union'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='union',
        ),
    ]
