# Generated by Django 2.2.3 on 2019-07-24 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(related_name='m_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='society',
            name='secretaries',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'secretary'}, related_name='s_societies', to=settings.AUTH_USER_MODEL),
        ),
    ]
