# Generated by Django 2.2.3 on 2019-08-22 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190724_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(related_name='mem_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='society',
            name='secretaries',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'secretary'}, related_name='sec_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='society',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
