# Generated by Django 2.2.5 on 2021-06-11 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190910_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='society',
            name='society_manager',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'society_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bm_approval',
            field=models.BooleanField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hq_approval',
            field=models.BooleanField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='created', max_length=15),
        ),
        migrations.AddField(
            model_name='union',
            name='society_managers',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'society_manager'}, related_name='sm_unions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='bm_approval',
            field=models.BooleanField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='hq_approval',
            field=models.BooleanField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='registered', max_length=15),
        ),
    ]
