# Generated by Django 2.2.5 on 2021-06-11 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_redefine_model_for_lender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='union',
            options={'verbose_name_plural': 'Headquarter'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='society_manager',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'society_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='secretary',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'secretary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to=settings.AUTH_USER_MODEL),
        ),
    ]
