# Generated by Django 2.2.5 on 2021-07-30 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_society_manager_to_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(null=True, related_name='mem_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='society',
            name='secretaries',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'secretary'}, null=True, related_name='sec_societies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
